-- ⚠ NOT THE SOURCE OF TRUTH — DO NOT RUN THIS.
--
-- The `api_keys` table is owned by the API worker (`packages/api`), defined in
-- Drizzle at packages/api/src/db/schema.ts and migrated via packages/api/drizzle.
-- The deployed table differs from what this file used to declare (it has an
-- extra `org_id uuid` FK to organizations, and uses a UNIQUE partial index
-- `idx_api_keys_active` on (project_id) WHERE is_active = true — NOT a full
-- UNIQUE(project_id)).
--
-- This worker only READS/WRITES api_keys rows (see ../api-keys/service.ts); it
-- does not own the schema. Running raw DDL from here would recreate the WRONG
-- table shape. To change the api_keys schema, edit packages/api/src/db/schema.ts
-- and apply it the way that package is reconciled (drizzle-kit push).
